### ISSUE TITLE
p4sock and p4tcp kernel modules?

### ISSUE THREAD

**Issue by ce107** [ParaStation/pscom#1]
How do I get to rebuild these kernel modules to use on a virtual NIC (throttled) multi-Gigabit Ethernet network? There does not seem to be an option to configure (or frankly much in terms of source). Was it dropped out?

**Comment by jensh** [comment]
Uhh... , the ancient p4sock kernel module... Yes, we dropped that 2010 where the kernel was numbered 2.6.x. The code still exists (somewhere), but would make more headache than help :smile: . Only bcm5700 and e1000 drivers were supported.
