### ISSUE TITLE
Glibc >= 2.34

### ISSUE THREAD

**Issue by acastanedam** [ParaStation/pscom#2]
Hi. The most recent version of Glibc has removed `__morecore` and
`__default_more` from the API, which causes compilation problems. I've
tried to add the explicit declaration of these hooks in the header
file of `psshmalloc` but I am not sure if this is the way to proceed,
on one hand, and in the other side it does not solve completely the
problem.

**Comment by spickartz** [comment]
Thanks for reporting this. We recognized this as well and fixed compilation problems on the `master` branch already. This fix will be part of the next release.
